# Generated by Django 3.2 on 2023-10-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField()),
                ('balloonContentHeader', models.CharField(max_length=255)),
                ('balloonContentBody', models.TextField()),
                ('balloonContentFooter', models.CharField(max_length=255)),
                ('iconImageHref', models.CharField(max_length=255)),
            ],
        ),
    ]
