# Generated by Django 3.2 on 2023-10-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='coordinates',
            field=models.CharField(max_length=255),
        ),
    ]
