# Generated by Django 3.2 on 2023-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0002_alter_office_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='coordinates',
            field=models.JSONField(),
        ),
    ]
